### ISSUE TITLE
Can't set a custom remote url anymore

### ISSUE THREAD

**Issue by twalpole** [edgarjs/ajaxful-rating#1]
Commit 48d2ed7a3f3b2a2939639e8824f41bc8f0fb8d8a broke the ability to set a custom remote url in gem 2.1.2

**Comment by edgarjs** [comment]
Thank you for letting me know.

Fix is on commit [a351e1](http://github.com/edgarjs/ajaxful-rating/commit/a351e1dd6bef2af7b10c16e6648c9028b77bbf34)
