### ISSUE TITLE
Display the rate for a user

### ISSUE THREAD

**Issue by tranquiliste** [edgarjs/ajaxful-rating#10]
Hello,

given that I have an article with n users who have rated the article, I would like to be able to list all the user with their rate. something like that:
<% @article.rates.users.each do |user| %>
   <%=  ratings_for @article, :static, user,  :show_user_rating => true %> 
<% end %>
and the stars being :static
is there a way to do that?
Thanks

**Comment by edgarjs** [comment]
Currently, there's only either static or a user instance. However, the stars will be static if:
1. There current user logged in, is not the one of the instance passed to the method.
2. The current user has already rated the article and the option `:allow_update` is false in the model. Like `ajaxful_rateable :allow_update => false`

So that way you can do something like:

<pre>
for user in @users
  ratings_for @article, user, :show_user_rating => true
end
</pre>


Regards.

**Comment by tranquiliste** [comment]
Thanks for your answer. 2 comments:
1 - the individual rates display in the title the global average (and not the current rate)
2 - this doen't work if I put :allow_update => true because I can rate on every single rate even if they are not mine (same if I am not logged in except that the rate action fails)

**Comment by edgarjs** [comment]
1. You mean the stars are correct but the title attribute is still global? Or the stars shows the global average even passing the `show_user_rating` option?
2. Are you caching the stars? The stars shouldn't be clickables if you're not logged in even if the `allow_update` is true.

**Comment by tranquiliste** [comment]
1. stars are correct. the title is global
2. No I am not caching the stars. And stars are clickable whether I am logged or not.

Thanks

**Comment by tranquiliste** [comment]
Hello where you able to reproduce the problem I mentionned?

**Comment by tranquiliste** [comment]
Hello I see that you consider this ticket as closed. Does it mean that you did not reproduce it?

**Comment by edgarjs** [comment]
Hello,
I see the problem on point 1. And couldn't replicate the second one.
I'm currently making some changes to the code to fix the point 1 and other bugs, so that commit could fix your problem on point 2.

I closed the ticket just to track which bugs I have already hit, but haven't done the commit yet. I think I'll label them instead to avoid confusion.

**Comment by tranquiliste** [comment]
Thanks very much for the update. I'll wait for the new version and will test it

**Comment by edgarjs** [comment]
Please try the new version 2.2.0 and let me know if you still have problems.

**Comment by tranquiliste** [comment]
Thanks.
A quick test without changing anythimg gives me the following error :undefined method `find_by_rater_id' for #Class:0x1030132f0
on 
<%= ratings_for @location, comment.user, :show_user_rating => true %>

and also stars are not displayed (meaning a 3.5 average gives no star to be yellowed). I'll try to make more tests later today.

Nicolas

**Comment by tranquiliste** [comment]
Forget the not yellowed stars, this was me not re-copying the css stylesheet

**Comment by tranquiliste** [comment]
And the error comes from the fact that you modified the rates table. I will change that and continue the tests.

Nicolas

**Comment by tranquiliste** [comment]
Hello,

I was able to make some tests and your new version corrected the title but not the fact that stars are clickable who ever is the user and even if he is not logged
In fact I loop on the comments for and diplay the stars
<%= ratings_for @location, comment.user, :show_user_rating => true %>
These are this star that are clickable.

Nicolas

**Comment by tranquiliste** [comment]
Note: Stars are not clickable if I put :allow_update => false (but I want to be able to update my notation

**Comment by edgarjs** [comment]
Sorry, I think I don't understand your problem now.
The clickable stars are displayed ONLY when a user is logged in OR if you pass a user instance to the helper as you do in your last comment.

The `:allow_update` option is to let the users update their already submitted ratings. You should set it to true if you want this behavior.

You can see the live demo here: http://axr.heroku.com and check the code to see how it is built.

Regards.

**Comment by tranquiliste** [comment]
Ok, let me explain what I have done.
I have my "location" which has been rated by several users (as well as commented) and I display all the different ratings assign by the different users so I loop trough the users and display the rating
<%= ratings_for @location, comment.user, :show_user_rating => true %>

Stars are correctly displayed but if I have the :allow_update set to true stars are also clickable.

**Comment by edgarjs** [comment]
Ok so that's because you are telling the plugin that the users who rated your "location" are able to update their own ratings (maybe if they change their mind about their rating). So if you don't want them to be clickable set `:allow_update` to false.

**Comment by tranquiliste** [comment]
Hello,

First thanks for your patience, and sorry for not being clearer.
In fact in my example when I am on the page where I display the rate of the different users, I can click  on any of the user rate whether they are mine or not and even if I am not logged in.

Nicolas

**Comment by edgarjs** [comment]
Ah ok I got it now. I was going for another path.
I see your problem, and you're right.

I've pushed v2.2.3 which fixes this by comparing the `current_user` with the owner of the rate. If you don't have a `current_user` helper method, you can pass the option `:current_user => @user` to use it as the logged in user.

This is for when you want list the raters and the stars be clickable for the logged in user. But if you only want to show the static stars, you could pass the option `:force_static  => true` which allows you to pass a user instance AND force the stars be static.

Check out the demo app source code to see it.

Thanks for bringing this up and your patience also.

**Comment by tranquiliste** [comment]
Great!! Thank you very much for correcting this. I won't be able to test it before this weekend but I'll let you know if it works.

Nicolas
PS: good idea for the :force_static, I was about to suggest it.

**Comment by tranquiliste** [comment]
Hello, I have done testing and noe it works as expected.

Thanks for this gem.
Nicolas

**Comment by anrake** [comment]
I wanted to something very similar and this took care of it.  Thanks !
