### ISSUE TITLE
undefined local variable or method `ajaxful_rateable' 

### ISSUE THREAD

**Issue by Set2005** [edgarjs/ajaxful-rating#11]
Hi there
       Can someone help me with this plz. I typed: ruby script/plugin install git://github.com/edgarjs/ajaxful-rating.git to install the plugin, then it just returned an new line, and it also creates a empty fold in the vendor\plugins\ajaxful-rating. As I follow the instructions I get "undefined local variable or method `ajaxful_rateable' for", It looks like the plugin never installed..  
Thx

**Comment by edgarjs** [comment]
Hi,

Try with this url instead:

`script/plugin install http://github.com/edgarjs/ajaxful-rating.git`

And if not, try with the gem on your environment.rb:

`config.gem "ajaxful_rating"`
