### ISSUE TITLE
SQLException

### ISSUE THREAD

**Issue by kimhoo** [edgarjs/ajaxful-rating#12]
SQLite3::SQLException: no such column: rates.user_id: SELECT sum("rates".stars) AS sum_stars FROM "rates" WHERE ("rates".user_id = 5) 

Does this project interfere with clearance gem?

**Comment by kimhoo** [comment]
By the way, I'm working on 2.2.1.1.

**Comment by edgarjs** [comment]
You need to regenerate your migration for rates on new version 2.2.x because a new column was added.

`script/destroy ajaxful_rating YourUserModelName`
`script/generate ajaxful_rating YourUserModelName`

**Comment by kimhoo** [comment]
That's weird. I set it all up today.

**Comment by kimhoo** [comment]
Same behavior.. I don't get it. I also am trying to use user as both rateable and rater. Though, reading through the issues, that should work, right?

**Comment by kimhoo** [comment]
No luck yet. I just compared your master version of migration file with my local one and they're exactly the same. That can't be it. Getting confused here.. :(

**Comment by edgarjs** [comment]
ok, let me check into it.

**Comment by kimhoo** [comment]
Ok, I'll check back tomorrow. It's been too many hours and need some sleep :) In this case we use clearance for our authentication model, which also generated our user (and set up for ajaxful_rating to use user model too). Put the route for user in the routes.rb, ran db:migrate, defined some dimensions, told User to be rater and rateable and now I'm stuck with this SQL issue.

That's about as much detail as I can give you now.

**Comment by kimhoo** [comment]
Ok, some trace:
[code]
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract_adapter.rb:219:in `log'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/sqlite_adapter.rb:172:in`execute'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/sqlite_adapter.rb:417:in `catch_schema_changes'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/sqlite_adapter.rb:172:in`execute'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/sqlite_adapter.rb:320:in `select'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in`select_all_without_query_cache'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:60:in `select_all'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:81:in`cache_sql'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/connection_adapters/abstract/query_cache.rb:60:in `select_all'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:661:in`find_by_sql'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:1548:in `find_every'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:615:in`find'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations/association_collection.rb:60:in `find'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations/association_collection.rb:400:in`find_target'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations/association_collection.rb:354:in `load_target'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations/association_proxy.rb:112:in`reload'
/Library/Ruby/Gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations.rb:1304:in `rates'
/Library/Ruby/Gems/1.8/gems/ajaxful_rating-2.2.1.1/lib/axr/model.rb:144:in`rates_sum'
/Library/Ruby/Gems/1.8/gems/ajaxful_rating-2.2.1.1/lib/axr/model.rb:154:in `rate_average'
/Library/Ruby/Gems/1.8/gems/ajaxful_rating-2.2.1.1/lib/axr/stars_builder.rb:18:in`show_value'
/Library/Ruby/Gems/1.8/gems/ajaxful_rating-2.2.1.1/lib/axr/stars_builder.rb:58:in `ratings_tag'
/Library/Ruby/Gems/1.8/gems/ajaxful_rating-2.2.1.1/lib/axr/stars_builder.rb:108:in`wrapper_tag'
/Library/Ruby/Gems/1.8/gems/ajaxful_rating-2.2.1.1/lib/axr/stars_builder.rb:23:in `render'
/Library/Ruby/Gems/1.8/gems/ajaxful_rating-2.2.1.1/lib/axr/helpers.rb:82:in`ratings_for'
/Users/kimhoo/workspace/softwareart/zzpmee/app/views/projects/show.html.erb:92:in `_run_erb_app47views47projects47show46html46erb'
[/code]

**Comment by kimhoo** [comment]
That line 92 is my ratings_for statement (sorry for the messy post)

**Comment by edgarjs** [comment]
Ok, I just pushed v2.2.2 with the fix. Please update and let me know. I've also implemented this feature in the demo page at http://axr.heroku.com

**Comment by kimhoo** [comment]
Thanks!

I got rid of the SQLException now (also when I removed user as being the rater, but now it works for a user being both). Though I get this message and I think that is because of clearance gem.

The UsersController is located elsewhere and I have tried to map the resource in the routes.rb included in the Clearance gem somewhere, but without success until now.

Processing ApplicationController#rate (for 127.0.0.1 at 2010-03-10 01:12:17) [POST]
  Parameters: {"small"=>"false", "action"=>"rate", "authenticity_token"=>"NFhhgpsbl/N286wdSUn/gAzgup2YT9/2Rmz63wmLAZ8=", "id"=>"5", "stars"=>"4", "controller"=>"users", "show_user_rating"=>"false", "dimension"=>"prijs"}

NameError (uninitialized constant UsersController):

**Comment by kimhoo** [comment]
Ok, I've got it.. First week of Ruby and I'm from a Java background, but I'm getting it now :) Seems as if my first post truely was an issue (lucky me :) ). I just needed to subclass the clearance controller, which all works now.

class UsersController < Clearance::UsersController
  def rate
    @user = User.find(params[:id])
    @user.rate(params[:stars], current_user, params[:dimension])
    render :update do |page|
      page.replace_html @user.wrapper_dom_id(params), ratings_for(@user, params.merge(:wrap => false))
      page.visual_effect :highlight, @user.wrapper_dom_id(params)
    end
  end
end

**Comment by edgarjs** [comment]
Cool, nice it's solved. Good luck on rails, you will love the ruby sugar.
