### ISSUE TITLE
2.2.1.1 & jruby sorting problem in AjaxfulRating::wrapper_dom_id()

### ISSUE THREAD

**Issue by mw46d** [edgarjs/ajaxful-rating#13]
Hello,
I had a problem with jruby (unrelated?) that the id's in the page source and the replacement after a rating update did not match. I changed the code a bit and it works for me now:

--- ajaxful-rating-2.2.1.1/lib/axr/model.rb~     2010-03-08 21:21:27.000000000 -0800
+++ ajaxful_rating-2.2.1.1/lib/axr/model.rb 2010-03-08 21:20:43.000000000 -0800
@@ -90,13 +90,13 @@
       options = options.symbolize_keys.slice(:small, :dimension)
       options = options.map do |k, v|
         if k == :dimension
-          v
-          v.to_s
       else
         v.to_s == 'true' ? k.to_s : "no-#{k}"
       end
     end
     prefix = "ajaxful_rating"
-      prefix << "_#{options.join('_')}" unless options.empty?
-      prefix << "_#{options.sort.join('_')}" unless options.empty?
     ApplicationController.helpers.dom_id(self, prefix)
   end

**Comment by mw46d** [comment]
OK, that did not work so well:-( Let's try that again:

<pre><code>
--- ajaxful-rating-2.2.1.1/lib/axr/model.rb~     2010-03-08 21:21:27.000000000 -0800
+++ ajaxful_rating-2.2.1.1/lib/axr/model.rb 2010-03-08 21:20:43.000000000 -0800
@@ -90,13 +90,13 @@
       options = options.symbolize_keys.slice(:small, :dimension)
       options = options.map do |k, v|
         if k == :dimension
-          v
+          v.to_s
         else
           v.to_s == 'true' ? k.to_s : "no-#{k}"
         end
       end
       prefix = "ajaxful_rating"
-      prefix << "_#{options.join('_')}" unless options.empty?
+      prefix << "_#{options.sort.join('_')}" unless options.empty?
       ApplicationController.helpers.dom_id(self, prefix)
     end
</code></pre>

**Comment by edgarjs** [comment]
Ok, thank you for your contribution. It's been added in v2.2.2

**Comment by jolmes** [comment]
I'm not sure if this is related...

The div id in the model page is fine, and is generated like so:

div class="ajaxful-rating-wrapper" id="ajaxful_rating_no-small_daycare_1">...</div

When clicked, the wrapper_dom_id function sends back the id with an extra underscore(just before the "no"): 

Element.update("ajaxful_rating__no-small_daycare_1",...)

If I replace "@daycare.wrapper_dom_id(params)" with "ajaxful_rating_no-small_daycare_1" everything works fine.

I'm working on this at the moment but if you see something that's obvious please let us know.

Thanks!!

v.2.2.3 with rails 2.3.5, on Windows 7 machine (ruby 1.8.6)

**Comment by edgarjs** [comment]
Hello,

I've made a small modification on the wrapper_dom_id. It should works now. Please try again and let me know.
