### ISSUE TITLE
Inline stars

### ISSUE THREAD

**Issue by pke** [edgarjs/ajaxful-rating#14]
I would like to inline the stars right next to the previous element in the HTML
I am using this HAML
- @tracks.each do |track|  
  %h2
  =link_to(track.title, track)
  =ratings_for(track, :wrap => false, :small => true)

And it keeps putting the rating below the link to the track.

**Comment by edgarjs** [comment]
That's because the helper actually puts a @div@ or @ul@ to wrap the stars. Those tags are block elements, you need to set their css style to @display: inline;@. But that's CSS, not ruby ;)
