### ISSUE TITLE
Rate model should be named Rating

### ISSUE THREAD

**Issue by pke** [edgarjs/ajaxful-rating#15]
Wouldn't that be a better name?
Could you add support for renaming the model in the options hash given to ajaxful_rateable?

ajaxful_rateable :class_name=>'Rating'

as it is already possible to customize the class_name in 
ajaxful_rater

**Comment by edgarjs** [comment]
Nice suggestion. I'll take it in account to implement.

**Comment by 8bithero** [comment]
Has this been implemented yet?

**Comment by edgarjs** [comment]
Not yet, I haven't had time to do it. If you're able to add this please feel free to send a pull request.
