### ISSUE TITLE
upgrading to 2.2

### ISSUE THREAD

**Issue by anrake** [edgarjs/ajaxful-rating#19]
I was using v2.1.5 but upgraded to take advantage of some of your improvements.  I'm getting the error the below error when I try to rate an object.  

NoMethodError (undefined method `rater=' for #Rate:0x106fc82b0):

What do I need to change from my old version to make it work with the new?  I manually changed user_id to rater_id in the Rates table, but what else should I do?

BTW, the above error only occurs when trying to rate something with no rating so far. If you update an existing rating there is no error.  

Thanks.

**Comment by edgarjs** [comment]
Hi,
You need to re-run the ajaxful_rating generator. Tell it to force overwrite of your files, just backup them first.

Sorry for this, but the improvements made this necessary.

**Comment by anrake** [comment]
No worries.  The improvements are worth the minor inconvenience.  Thanks so much for your support and continued development.  This worked perfectly and fixed the css problems too.
