### ISSUE TITLE
uninitialized constant

### ISSUE THREAD

**Issue by gregorym** [edgarjs/ajaxful-rating#20]
Hi,
I followed the installation instruction but I get an error n every page of my web site.
Here is the error:
uninitialized constant Defi::Rate

Log:
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:105:in `const_missing'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:2199:in`compute_type'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/core_ext/kernel/reporting.rb:11:in `silence_warnings'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/base.rb:2195:in`compute_type'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/reflection.rb:156:in `send'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/reflection.rb:156:in`klass'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/reflection.rb:187:in `quoted_table_name'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations.rb:1416:in`configure_dependency_for_has_many'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/activerecord-2.3.5/lib/active_record/associations.rb:824:in `has_many'
(eval):3:in`has_many'
/Library/Ruby/Gems/1.8/gems/ajaxful_rating-2.2.4/lib/axr/model.rb:21:in `ajaxful_rateable'
/Users/gregorymarcilhacy/Documents/projets/trunk-capoupascap/app/models/defi.rb:2
/Users/gregorymarcilhacy/Documents/projets/trunk-capoupascap/app/controllers/home_controller.rb:4:in`index'

Any idea why?

**Comment by gregorym** [comment]
My mistake, I didn't generate the migration file.

Greg

**Comment by edgarjs** [comment]
Hi, good it works now.
