### ISSUE TITLE
RJS Error

### ISSUE THREAD

**Issue by pepeperez** [edgarjs/ajaxful-rating#21]
Hello,

I've just updated from 2.1.3 to 2.2.4. I have executed again the ajaxful_rating generator, I have updated the database, the images and the stylesheet.

Everithing is working but when I try to rate an object, it raises a pop up that says:

```
    RJS error:

   TypeError: element is null
```

And then a second pop up that says:
          Element.update("_ajaxful_rating_no-small_publication_2", "<ul class=\"ajaxful-rating\"><li class=\"show-value\" style=\"width: 80.0%\">Global rating average: 4.0 out of 5</li><li><a class=\"stars-1\" href=\"#\" onclick=\"new Ajax.Request('/publications/2/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=1' + '&amp;authenticity_token=' + encodeURIComponent('oJ6sB5YMQPgws7HCtvHhcJ9y5I91gc5gKQE7XEN6o6c=')}); return false;\" title=\"Rate 1 out of 5\">1</a></li><li><a class=\"stars-2\" href=\"#\" onclick=\"new Ajax.Request('/publications/2/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=2' + '&amp;authenticity_token=' + encodeURIComponent('oJ6sB5YMQPgws7HCtvHhcJ9y5I91gc5gKQE7XEN6o6c=')}); return false;\" title=\"Rate 2 out of 5\">2</a></li><li><a class=\"stars-3\" href=\"#\" onclick=\"new Ajax.Request('/publications/2/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=3' + '&amp;authenticity_token=' + encodeURIComponent('oJ6sB5YMQPgws7HCtvHhcJ9y5I91gc5gKQE7XEN6o6c=')}); return false;\" title=\"Rate 3 out of 5\">3</a></li><li><a class=\"stars-4\" href=\"#\" onclick=\"new Ajax.Request('/publications/2/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=4' + '&amp;authenticity_token=' + encodeURIComponent('oJ6sB5YMQPgws7HCtvHhcJ9y5I91gc5gKQE7XEN6o6c=')}); return false;\" title=\"Rate 4 out of 5\">4</a></li><li><a class=\"stars-5\" href=\"#\" onclick=\"new Ajax.Request('/publications/2/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=5' + '&amp;authenticity_token=' + encodeURIComponent('oJ6sB5YMQPgws7HCtvHhcJ9y5I91gc5gKQE7XEN6o6c=')}); return false;\" title=\"Rate 5 out of 5\">5</a></li></ul>");
    new Effect.Highlight("_ajaxful_rating_no-small_publication_2",{});

After that, the stars remain blank, but when I reload the page, I realize that the rating has been stored.

Any suggestion??

Thank you very much in advance, keep up this great work!!

**Comment by matellis** [comment]
Add a dimension to your model & view. Everything will work fine if you have no dimension except the ajax update. It looks like it makes names in the RJS like 'element__foo' (note the double underscore). Add a single element and you now get 'element_rjs_foo'. There is a branch by odorcicd that partially resolves this issue at http://github.com/odorcicd/ajaxful-rating/tree/

Good luck!

**Comment by edgarjs** [comment]
Yes, this is a bug caused by: http://github.com/edgarjs/ajaxful-rating/issues/#issue/26

Keep posted for the fix.
