### ISSUE TITLE
qeustion about rating in print

### ISSUE THREAD

**Issue by realalien** [edgarjs/ajaxful-rating#25]
Hi! It occurs to me that when I try to print the web page, the rating does not look nice, i.e. it's 10 line   s of number with underline instead of somewhat a horizontal bar.

I don't know how to solve the problem, would you please give some advices?

**Comment by realalien** [comment]
OK, a easier way for me is to create  a 'print' handling action. :)

**Comment by edgarjs** [comment]
Are you applying a different CSS for printing? If so, you should still including the ajaxful-rating one.
