### ISSUE TITLE
spaces in dimension names

### ISSUE THREAD

**Issue by badnaam** [edgarjs/ajaxful-rating#28]
Is it ok to have dimensions like "Product And Service Quality"?

If yes, what would be the cached average rating column name?

Thanks

**Comment by edgarjs** [comment]
The dimension should be a symbol, which implies you can use underscores. You can label it whatever you want, but for example we could add a dimension:

`:product_and_service_quality`

Then the cache column would be `rating_average_product_and_service_quality`
