### ISSUE TITLE
usage of rails_xss plugin with rails 2.3.8 break output

### ISSUE THREAD

**Issue by 2case** [edgarjs/ajaxful-rating#29]
under rails 2.3.8 (ruby 1.9.1) the usage of the rails_xss plugin (adviced by rails core team) the output break and is escaped.

any solution? for now i "hacked" the gem directly and add an html_safe! in the function ratings_tag to the stars.join

**Comment by edgarjs** [comment]
v2.2.7 of the plugin now handles this. Please update your gem.
Thanks for report.

**Comment by 2case** [comment]
sorry, but the function ratings_tag handle nothing and all li's still are NOT html_safe so the output is escaped. as i wrote: the join is the problem, html_safe does NOT inherit to any new strings!

**Comment by 2case** [comment]
take a look at http://gist.github.com/437491 that work for me

**Comment by edgarjs** [comment]
Ok I thought `html_safe` was inheriting. Thanks for the patch, pushed.

**Comment by 2case** [comment]
great, work now :) thanks for your support!
