### ISSUE TITLE
Multiple ratings_for on one page

### ISSUE THREAD

**Issue by davidcelis** [edgarjs/ajaxful-rating#32]
Hi,

On one of my views, I call ratings_for on like objects found via a block. If there are more than one objects found, the stars display fine for each one. However, when submitting a rating for any of these itemts, the stars for the first item change while the stars that should be associated with the item do not.

However, the ratings seems to submit fine for every item after the first. However, the first item will rate once and then never update if its stars are changed.

**Comment by edgarjs** [comment]
Hello,

Sorry could you explain a little more detailed or with an example? I don't understand the issue.

Thanks.
