### ISSUE TITLE
Aggregate ratings

### ISSUE THREAD

**Issue by davidcelis** [edgarjs/ajaxful-rating#33]
Hey again. Just wonder if there is any way to aggregate ratings for multiple objects. Here's an example...

I have a course object which has several rateable lessons. I don't want to make a course rateable, but I do want to be able to display an "overall rating" for the course which is simply the average rating across lessons (if there are three lessons with ratings of 5, 2, and 1 then I would want to be able to display 2.7 stars.

Alternatively, if there's a method that I can pass in a value and just have it display that in stars, I know how to calculate this average beforehand and could just pass it to this method. Do either of these functionalities exist?

**Comment by edgarjs** [comment]
Hi,

There's no automatic aggregation for parents. So you could calculate the average as you say. You can add the configuration to your course model (even when it doesn't get rated) and overwrite the instance method `rate_average` (there could be where you get the calculation), the method receive two params: `rate_average(true, options[:dimension])`. But like I say you need to add the `ajaxful_rateable` call to make all other methods available for the helper.
