### ISSUE TITLE
Access to number of ratings

### ISSUE THREAD

**Issue by skogul** [edgarjs/ajaxful-rating#36]
I apologize if I'm missing something, but it seems like the rating system would be much more suited for practical use if the number of ratings is accessible.

For example, a user might want to know if 100 people have given an article a good rating, in which case the recommendation is very reliable, vs one person, in which case the recommendation is not as reliable.

**Comment by skogul** [comment]
oops, figured it out.

**Comment by edgarjs** [comment]
Good, you can check the demo app also for this example. http://axr.heroku.com
