### ISSUE TITLE
html_safe breaaks from 2.2.6 to 2.2.8

### ISSUE THREAD

**Issue by jalvarezsamayoa** [edgarjs/ajaxful-rating#37]
I just updated the gem from 2.2.6. to 2.2.8 in a production application and my cucumber test starting breaking with this error

undefined method `html_safe' for #<String:

when doing <%= ratings_for @document, :static %>

Like I said this was a working application with 2.2.6, any guidance on how to fix this?
## this is my environment.rb 

  config.gem "formtastic"
  config.gem "authlogic"
  config.gem 'mislav-will_paginate', :version => '~> 2.3.11', :lib => 'will_paginate', 
  :source => 'http://gems.github.com'
  config.gem 'thoughtbot-paperclip', :lib => 'paperclip', :source => 'http://gems.github.com'
  config.gem 'sitemap_generator', :lib => false, :source => 'http://gemcutter.org'
  config.gem 'pdf-toolkit', :lib => 'pdf/toolkit'
  config.gem "ajaxful_rating", :version => '2.2.6'

**Comment by edgarjs** [comment]
Please update to version 2.2.8.1

**Comment by jalvarezsamayoa** [comment]
problem solved :D
