### ISSUE TITLE
RJS Error

### ISSUE THREAD

**Issue by cwills** [edgarjs/ajaxful-rating#40]
I had previously used the edgarjs-ajaxful_rating gem. I'm now trying to get setup with the new ajaxful_rating gem and I'm running into an issue. When I rate an article I receive an RJS error.

Element.update("ajaxful-rating-link-8167", "<ul class=\"ajaxful-rating\"><li class=\"show-value\" style=\"width: 80.0%\">Global rating average: 4.0 out of 5</li><li><a class=\"stars-1\" href=\"#\" onclick=\"new Ajax.Request('/links/8167/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=1' + '&amp;authenticity_token=' + encodeURIComponent('I79P1IT8pNoG/zDZReMhQmjlw3TYAAjhoF3/ms4LHDQ=')}); return false;\" title=\"Rate 1 out of 5\">1</a></li><li><a class=\"stars-2\" href=\"#\" onclick=\"new Ajax.Request('/links/8167/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=2' + '&amp;authenticity_token=' + encodeURIComponent('I79P1IT8pNoG/zDZReMhQmjlw3TYAAjhoF3/ms4LHDQ=')}); return false;\" title=\"Rate 2 out of 5\">2</a></li><li><a class=\"stars-3\" href=\"#\" onclick=\"new Ajax.Request('/links/8167/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=3' + '&amp;authenticity_token=' + encodeURIComponent('I79P1IT8pNoG/zDZReMhQmjlw3TYAAjhoF3/ms4LHDQ=')}); return false;\" title=\"Rate 3 out of 5\">3</a></li><li><a class=\"stars-4\" href=\"#\" onclick=\"new Ajax.Request('/links/8167/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=4' + '&amp;authenticity_token=' + encodeURIComponent('I79P1IT8pNoG/zDZReMhQmjlw3TYAAjhoF3/ms4LHDQ=')}); return false;\" title=\"Rate 4 out of 5\">4</a></li><li><a class=\"stars-5\" href=\"#\" onclick=\"new Ajax.Request('/links/8167/rate', {asynchronous:true, evalScripts:true, method:'post', parameters:'dimension=&amp;show_user_rating=false&amp;small=false&amp;stars=5' + '&amp;authenticity_token=' + encodeURIComponent('I79P1IT8pNoG/zDZReMhQmjlw3TYAAjhoF3/ms4LHDQ=')}); return false;\" title=\"Rate 5 out of 5\">5</a></li></ul>");
new Effect.Highlight("ajaxful-rating-link-8167",{});

The error appears to be caused by my div id...

<div class="ajaxful-rating-wrapper" id="ajaxful_rating_no-small_link_8167">

Instead of 'ajaxful-rating-link-8167' it is 'ajaxful_rating_no-small_link_8167'. Any idea how to resolve this? Where is the "no-small" coming from?

Thank you,
Chris

**Comment by cwills** [comment]
Solved the problem by changing a line in my links_controller to...

id = "ajaxful_rating_no-small_#{!params[:dimension].blank? ? "#{params[:dimension]}-" : ''}link_#{@link.id}"

Now everything works.

Thanks,
Chris

**Comment by edgarjs** [comment]
Glad you solved the problem. This technique is already added in a method called `wrapper_dom_id` so you can just call `@link.wrapper_dom_id(params)` to build the id for the div.
