### ISSUE TITLE
can't install gem on rails 3

### ISSUE THREAD

**Issue by humanbagel** [edgarjs/ajaxful-rating#47]
I'm a rails newbies so please forgive me if i'm doing something stupid.

I am trying to install the rails 3 beta of ajaxful_rating by doing 'gem install ajaxful_rating --pre', it says it installed.  but i can't find the generators anywhere?

**Comment by odorcicd** [comment]
Tested on a fresh install, said the gem was installed and 'rails g' displayed that the generator for ajaxful rating was there. Not sure what the issue can be, unfortunately.

**Comment by humanbagel** [comment]
turns out i had ajaxful_rating 2.2.8.2 installed as well as the 3.0.0beta3.  once i uninstalled 2.2.8.2, i was able to run rails generate ajaxful_rating myusertable
