### ISSUE TITLE
error: "Could not find generator ajaxful_rating."

### ISSUE THREAD

**Issue by ghost** [edgarjs/ajaxful-rating#48]
While trying to run "rails g ajaxful_rating User" command i get this error:

"Could not find generator ajaxful_rating."

The gem is installed, I'm working on Rails 3. How can I make it work?

**Comment by odorcicd** [comment]
Someone posted an issue stating that they had an older version of ajaxful_rating installed as well as the Rails 3 gem, which conflicted. Try removing any other versions.

**Comment by ghost** [comment]
removing older versions seemed to solve that problem. Thank You.

**Comment by TriKro** [comment]
I guess I'm the dummy now. I have the same issue, but only the latest gem installed.

**Comment by lenorris** [comment]
I also have the same issue. If I view the generators with 'rails g' no ajaxful-rating generator is shown.

I only have the latest gem installed.

**Comment by edgarjs** [comment]
Try adding the gem to the development group in your gemfile, either:

`gem 'ajaxful_rating', '3.0.0.beta3', :group => :development`

or

<pre>
group :development do
  gem 'ajaxful_rating', '3.0.0.beta3'
end
</pre>
