### ISSUE TITLE
error: "undefined method `rate_average' for nil:NilClass"

### ISSUE THREAD

**Issue by ghost** [edgarjs/ajaxful-rating#49]
I'm getting this error:

"undefined method `rate_average' for nil:NilClass"

when trying to use this gem. This is the view code:

<%= ratings_for @comment, :remote_options => {:url => rate_comment_path(@comment)} %>

Comment table has a rating_average column.

**Comment by edgarjs** [comment]
This is probably because you're not finding correctly your @comment instance in the controller. Check that your @comment variable is not nil in any/both your view and controller.
