### ISSUE TITLE
Show only the user rates.

### ISSUE THREAD

**Issue by alextakitani** [edgarjs/ajaxful-rating#5]
IS there any way of showing only the current user rates with

rates_for @model, :dimension=>:x   ?

Or it will always bring together the average of all votes?

Tks!

**Comment by edgarjs** [comment]
The helper shows only the average, but you can hack it a bit to show:

`@article.rate_by(User.first, :any_dimension)`

**Comment by alextakitani** [comment]
Tks! Don't you think this default behaviour is a bit odd? 
Should't it be a :show_average option?

**Comment by edgarjs** [comment]
Uhm, sounds interesting but maybe not as the default and the option could be `:show_own`

**Comment by rmichela** [comment]
Has :show_own been implemented? If not, can you please clarify the hack above?

Thanks :)

**Comment by edgarjs** [comment]
Not yet implemented.
The "hack" above is a method that is already there and you can use to get the rate made by a user.

**Comment by rmichela** [comment]
Completed. See email.

**Comment by edgarjs** [comment]
Just fyi. The change has been implemented by andypayne in the last commits.
The option is `:show_user_rating => true`
`ratings_for @article, :show_user_rating => true`
