### ISSUE TITLE
Ratings disappear on show/hide (2.2.8.2)

### ISSUE THREAD

**Issue by bilditup1** [edgarjs/ajaxful-rating#51]
Ratings disappear when the div that they appear in are hidden via a simple jQuery('.blah').hide(); In other words when calling 'show' on the same div, the rating do not show up. They are still there in the HTML but are no longer styled, so I suppose this is some kind of CSS issue? 
Is there any way around this?
I am running 2.2.8.2 with Rails 2.3.8.

**Comment by bilditup1** [comment]
Figured it out. Sloppy js was hiding all child divs under the parent, but not unhiding them. Someone should ban me :(

**Comment by odorcicd** [comment]
Alright, I'll contact the github admins!
