### ISSUE TITLE
Doesn't work with nesting routes

### ISSUE THREAD

**Issue by angela1111** [edgarjs/ajaxful-rating#52]
Don't know how to get the plugin to work with nesting.
map.resources :chapters do |chapter|
chapter.resources :submissions, :member => {:rate => :post} 
end

is the route and the show page is:

Your rating: <%= ratings_for @submission, :force_static => true, :small => true, :show_user_rating => true %>

**Comment by edgarjs** [comment]
Try passing the url to the view helper: `<%= ratings_for @article, :remote_options => {:url => rate_admin_article_path(@article)} %>`

**Comment by angela1111** [comment]
thanks!
