### ISSUE TITLE
Objects with no rating and inline rating

### ISSUE THREAD

**Issue by Joesavage1** [edgarjs/ajaxful-rating#54]
Hi,

I'm working on a project for which I'm using ajaxful-rating for the rating system.
I have it all working correctly and all is good - however I'm having a few issues.

Firstly, when some of the objects that can be rated by users do not yet have a rating - the starts are invisible (unless the user hovers over). This might just be the bad colour quality of my screen (light colours are sometimes just displayed as white) - but I need the no rating image to be more obvious (maybe some grey stars?).

Secondly I need the stars to be able to be displayed inline. For example:
&lt;strong&gt;Speed:&lt;/strong&gt;<%= ratings_for @object, :dimension => :quality %>

Currently - the above line displays "Speed:" and then the stars below. How can I make these be on the same line?

Thanks in advance,

Joe

**Comment by Joesavage1** [comment]
Managed to change the first problem of the invisible stars by editing the image files in the images folder - but still cannot figure out how to make the rating starts display on the same line as other content.

Please Help,

Thanks In Advance,

Joe

**Comment by edgarjs** [comment]
Hi, you just need to take a look at the css file and customize it to your needs.

As for the images, if you want the psd files you can grab them here: http://aws3-edgarjs-zips.s3.amazonaws.com/ajaxful_rating_stars.zip
