### ISSUE TITLE
undefined method `singular_class_name' for ActionController::RecordIdentifier:Module

### ISSUE THREAD

**Issue by mvitenkov** [edgarjs/ajaxful-rating#57]
My view page looks like:
<% if !current? and (expert? or public_expert?)%>
    Workable:<%= ratings_for @user, :dimension => :workable, :show_user_rating => true %>
    Completed:<%= ratings_for @user, :dimension => :completed, :show_user_rating => true %>
    Designed:<%= ratings_for @user, :dimension => :designed, :show_user_rating => true %>
  <%end%>

My model:
class User < ActiveRecord::Base
...
ajaxful_rater
  ajaxful_rateable :stars => 10, :dimensions => [:workable, :completed, :designed], :allow_update => true

My routes:
map.resources :users, :member => {:rate => :post} do |nested|
    nested.resources :posts
  end

My environment:
ruby 1.8.7(patch 352)
rails 3.0.7
rubygems 1.8.6
webrick server

Gemfile: 
gem 'ajaxful_rating', :git => 'git://github.com/edgarjs/ajaxful-rating.git', :branch => "rails3"

Note: everything worked fine for a long time, but seems like the 'ajaxful_rating' gem became broken after update.
Could you please look at this? I met the same problem here: http://stackoverflow.com/questions/7157882/ratings-for-getting-error-in-ajaxful-rating-jquery

Thanks and appreciate for your work, keep going!

**Comment by edgarjs** [comment]
Hey,

As you say on SO, you need to update the version of the gem 'beta6', I'll check the problem on the stars though.

**Comment by mvitenkov** [comment]
Thank you, Edgar :)
