### ISSUE TITLE
Hi, not able to submit rates....

### ISSUE THREAD

**Issue by timfong888** [edgarjs/ajaxful-rating#6]
Hi, I followed the instructions...needed to add a rake db:migrate that wasn't there...but anyway...I can display the rates when I put it into the show...but how do I submit?  No ajax behavior occurs when I mouse over it....am I missing something? 

I checked out the demo....just saw code in the show -- and I added the def rate to the ratedobject model.

**Comment by edgarjs** [comment]
You don't need to add any method to the model, that's added automatically when you put the line `ajaxful_rateable :dimensions => [:speed, :beauty, :price]` in your model.

**Comment by dannytanwy** [comment]
Having a similar problem, but seem to have problems with my routes, I am getting the following error (undefined method `rate' for nil:NilClass)... 

I have the following in my routes
map.resources :documents, :member => {:rate => :post}

Documents Controller
  def rate
    @document.rate(params[:stars], current_user, params[:dimension])
    id = "ajaxful-rating-#{!params[:dimension].blank? ? "#{params[:dimension]}-" : ''}document-#{@document.id}"
    render :update do |page|
      page.replace_html id, ratings_for(@document, :wrap => false, :dimension => params[:dimension], :small_stars => params[:small_stars])
      page.visual_effect :highlight, id
    end
  end

View
<%= ratings_for @document, :dimension => :discussable %>

Document Model
ajaxful_rateable :stars => 5, :dimensions => [:discussable], :allowupdate => true

Am I missing out something here?

**Comment by edgarjs** [comment]
Do you find the `@document` instance before trying to rate it? I didn't put it because it is implicit.

<pre>
def rate
  @document = Document.find(params[:id])
  @document.rate(........)
end
</pre>


Hope this helps you.

**Comment by dannytanwy** [comment]
Great! Thanks Edgar, this work like a charm :) thanks for your help!
