### ISSUE TITLE
still not able to actually rate -- stars remain blank

### ISSUE THREAD

**Issue by timfong888** [edgarjs/ajaxful-rating#7]
In my Vendors Controller I put the following method:

  def rate
    @vendor.rate(params[:stars], current_user, params[:dimension])
    id = "ajaxful-rating-#{!params[:dimension].blank? ? "#{params[:dimension]}-" : ''}vendor-#{@vendor.id}"
    render :update do |page|
      page.replace_html id, ratings_for(@vendor, :wrap => false, :dimension => params[:dimension], :small_stars => params[:small_stars])
      page.visual_effect :highlight, id
    end
  end

I then display in the view#show:
<%= ratings_for @vendor %>

I can mouse over it and see that it is 0.0/4.0 but there isn't a way to actually submit a rating.

**Comment by edgarjs** [comment]
Try to see the generated HTML code, are the stars anchor tags (`<a>`) or only list items (`<li>`)?

**Comment by fespino** [comment]
Im having the same problem, that´s the generated HTML code:

<div class="ajaxful-rating-wrapper" id="ajaxful-rating-valoracion-plan-18">
    <ul class="ajaxful-rating small-star">
        <li class="current-rating" style="width:0.0%">Current rating: 0.0/5</li>
        <li><span class="stars-1" title="Current rating: 0.0/5">1</span></li>
        <li><span class="stars-2" title="Current rating: 0.0/5">2</span></li>
        <li><span class="stars-3" title="Current rating: 0.0/5">3</span></li>
        <li><span class="stars-4" title="Current rating: 0.0/5">4</span></li>
        <li><span class="stars-5" title="Current rating: 0.0/5">5</span></li>
    </ul>
</div>

**Comment by edgarjs** [comment]
Ok so for what I can see in the code you're not logged in. The helper will detect wheter or not there is a current_user. Try signing up and you'll see the links.
