### ISSUE TITLE
Can a user to rate the same object more than one time

### ISSUE THREAD

**Issue by iotriado** [edgarjs/ajaxful-rating#70]
Hello,
I want to ask if a user can rate more than once the same object. For example i want a user to leave rating every time he/she buys a product. So if i buy 10 times the same product i will leave 10 eavaluations for this products
Br
Triantopoulos Ioannis

**Comment by edgarjs** [comment]
Hello, currently there's no way to allow a user rate the same object. It will update the previous value.

**Comment by iotriado** [comment]
OK thanks for your response
