### ISSUE TITLE
Does't work properly with rails 3.2.3

### ISSUE THREAD

**Issue by tomkrus** [edgarjs/ajaxful-rating#71]
If we have new stuff in rails:

config.active_record.whitelist_attributes = true

get error

Can't mass-assign protected attributes:

/axr/model.rb:in 'rate'....

The question is where to put in 'model.rb' attr_accessible?

---

I just create model rate

**Comment by edgarjs** [comment]
well, you put it in any place within your model (normally at the top). The rate model is generated by the gem, don't need to create it manually.

**Comment by tomkrus** [comment]
Yes, of course, I forgot about this, my application is already some years.
