### ISSUE TITLE
Helpers

### ISSUE THREAD

**Issue by pwgustafson** [edgarjs/ajaxful-rating#72]
I can't seem to find how to user any of the helpers (if there are any)

I have an article model that is rateable on multiple dimensions, I would like to be able to get the global rating of a specific dimension, and across all dimensions...

Is this possible? 

Thanks!

**Comment by edgarjs** [comment]
You can find the instructions in the README file, in the Use it section, here's the link:

https://github.com/edgarjs/ajaxful-rating#use-it

**Comment by pwgustafson** [comment]
Yeah, I saw that...

I was curios what other helpers are available...If I wanna get the scores/ratings of article in other places besides the actual ratings area... 

I see that I can do:

```
@article.rates(:data_presentation)
```

Is there a way to get the ratings for all dimensions?

**Comment by edgarjs** [comment]
Oh I get it. Well, no, you'll need to call that method for each dimension. Or call it without arguments to have an average of all dimensions.
