### ISSUE TITLE
SQL errors with MySQL

### ISSUE THREAD

**Issue by bemurphy** [edgarjs/ajaxful-rating#8]
I'm testing out the demo app.  It works fine with sqlite3, but blows up in spots when using MySQL.  For example:

car.raters
ActiveRecord::StatementInvalid: Mysql::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '[id] = r.[user_id] WHERE r.[rateable_id] = 1 AND r.[rateable_type] = 'Car'' at line 1: SELECT DISTINCT u.\* FROM users u INNER JOIN rates r ON u.[id] = r.[user_id] WHERE r.[rateable_id] = 1 AND r.[rateable_type] = 'Car'

I'm slightly behind on mysql version, fyi (5.0.51a).  Perhaps that's related.

**Comment by edgarjs** [comment]
I haven't received any issue similiar to this, let me check if I can replicate. In the mean time you could update your mysql version to see if it's that. :)

**Comment by edgarjs** [comment]
I just tried with Mysql 5.1.30 and didn't had a problem. All works fine.

**Comment by bemurphy** [comment]
Thanks for testing it out on your end, Edgar.  I ripped the square brackets out and it seemed to work as I'd expect then.  I'm not familiar with that syntax though, I should go look it up to learn it.

Thanks again for your time.

**Comment by edgarjs** [comment]
Ah, sorry for don't update here. I actually found the same error as you mention because of the square brackets. I've removed them from the sql but haven't committed, as I'm in the middle of the development for the next version of the plugin.

**Comment by edgarjs** [comment]
Please try the new version 2.2.0 and let me know if you still have problems.
